### ISSUE TITLE
`--force` does not install the specified spec as expected

### ISSUE THREAD

**Issue by thatlittleboy** [pypa/pipx#929] opened 2023-01-21 05:13 UTC
**Describe the bug**
I use `pipx install --force` intending to install over an existing venv, but nothing seems to change (seems like it reuses the previous spec?). More on this below.

I'm using pipx 1.1.0 on python 3.9, macOS 12.5.1.

**How to reproduce**

1. ```bash
   pipx install git+ssh://git@github.com/nedbat/dinghy@1.0.0
    ```
    In this version, the `digest.py` file contains a call to `render_jinja_to_file` where the first argument is a literal string. You can verify it on Github source [here](https://github.com/nedbat/dinghy/blob/739176d01cdbf284e330f69afc3e57c3450ca1be/src/dinghy/digest.py#L524).
    <img src="https://user-images.githubusercontent.com/30731072/213844025-8563e22e-2953-490d-9afe-adcb3ae65731.png" width=400>
    Verify the locally installed `dinghy` package `digest.py` also looks like this, `cat ~/.local/pipx/venvs/dinghy/lib/python3.9/site-packages/dinghy/digest.py`
1. Now, force install the latest HEAD commit (this is a couple of commits after the `1.0.0` tag).
    ```bash
    pipx install --force git+ssh://git@github.com/nedbat/dinghy@b4e750aa2bf0f1d436e7af8004a24bd94741f995
    ```
    In this version, the same `digest.py` file contains a call to `render_jinja_to_file`, but with a different first argument. You can verify on Github source [here](https://github.com/nedbat/dinghy/blob/b4e750aa2bf0f1d436e7af8004a24bd94741f995/src/dinghy/digest.py#L536).
    <img src="https://user-images.githubusercontent.com/30731072/213844287-b439401e-0fef-48fa-bcaa-3ec3e49decee.png" width=400>
1. After installing, check the locally installed file again: `cat ~/.local/pipx/venvs/dinghy/lib/python3.9/site-packages/dinghy/digest.py`. The state of the `digest.py` file is the same as when it was `1.0.0`, not the HEAD commit.

---

You can also **reverse the steps**: uninstall `dinghy` first, then install the HEAD commit, then force install the `1.0.0` commit. You'll see the `digest.py` file is the state as of HEAD, not the `1.0.0`. So it seems that `--force` is not doing what I expect?

<br><br>

**Expected behavior**

The venv should be overwritten when using `--force`. In my example, if we install `1.0.0` then `HEAD`, the local `digest.py` file should look like what I shown in step 2, not step 1.

**Comment by meowmeowmeowcat** [comment] 2023-01-21 06:29
This is probably a duplicate of https://github.com/pypa/pipx/issues/582.

**Comment by thatlittleboy** [comment] 2023-01-21 06:43
Yep, seems like it, feel free to close this issue as duplicate.

Any plans to fix this behaviour / document the current behaviour more clearly though?

**Comment by meowmeowmeowcat** [comment] 2023-02-02 13:14
I've opened #933 to fix it.

**Closed** 2023-07-03 11:33 UTC
