### ISSUE TITLE
ensurepath falsely detecting C:\Users\...\AppData\Roaming\Python\Python310\Scripts as being in PATH on Windows

### ISSUE THREAD

**Issue by Vuizur** [pypa/pipx#978] opened 2023-05-15 11:09 UTC
As instructed by the terminal/tutorial on https://pypa.github.io/pipx/, I ran `.\pipx ensurepath` to add the PATH to Windows. I got this message:

```
Success! Added C:\Users\...\.local\bin to the PATH environment variable.
C:\Users\...\AppData\Roaming\Python\Python310\Scripts is already in PATH.

Consider adding shell completions for pipx. Run 'pipx completions' for
instructions.

You will need to open a new terminal or re-login for the PATH changes to take  
effect.

Otherwise pipx is ready to go! ✨ 🌟 ✨
```
However, the part about `C:\Users\...\AppData\Roaming\Python\Python310\Scripts` was not true, I restarted the terminal/my PC, but it wouldn't detect pipx, only adding the listed path manually fixed the problem. I did have some similar folders in my PATH (C:/Python10/Scripts), so maybe this could be the reason (and the regex to detect already existing values in PATH maybe is not specific enough).
(It did add `C:\Users\...\.local\bin` correctly though).

PS: Thanks a lot for maintaing this project!

**Comment by uranusjr** [comment] 2023-05-15 12:44
A way to reproduce the issue (with say a virtual machine) would be helpful.

**Comment by Vuizur** [comment] 2023-05-16 19:29
I looked now a bit into the pipx code and think the reason might be that if you execute a python script in a specific directory that is not in PATH and then call `print(userpath.in_current_path(os.getcwd()))` it still prints `True`.

**Comment by Vuizur** [comment] 2023-05-20 06:49
I opened an issue here: https://github.com/ofek/userpath/issues/45

**Comment by dukecat0** [comment] 2023-08-26 08:15
Closing this since the fix in userpath was merged.

**Closed by dukecat0** 2023-08-26 08:15 UTC
Labels: upstream
