### ISSUE TITLE
Injected shebang does not escape whitespace in interpreter path

### ISSUE THREAD

**Issue by j-hui** [pypa/pipx#1212] opened 2024-01-16 12:15 UTC
**Describe the bug**

After I've installed a package, whitespace is not properly escaped in the shebang.

**How to reproduce**

```console
$ pipx install --verbose pass2csv
pipx >(setup:853): pipx version is 1.4.2
pipx >(setup:854): Default python interpreter is '/opt/homebrew/opt/python@3.12/libexec/bin/python'
pipx >(package_name_from_spec:370): Determined package name: pass2csv
pipx >(package_name_from_spec:371): Package name determined in 0.0s
creating virtual environment...
pipx >(run_subprocess:168): running /opt/homebrew/opt/python@3.12/libexec/bin/python -m venv --without-pip /Users/j-hui/Library/Application Support/pipx/venvs/pass2csv
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(run_subprocess:168): running /Users/j-hui/Library/Application Support/pipx/venvs/pass2csv/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:168): running /Users/j-hui/Library/Application Support/pipx/shared/bin/python-c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:168): running /Users/j-hui/Library/Application Support/pipx/venvs/pass2csv/bin/python --version
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: pass2csv
installing pass2csv...
pipx >(run_subprocess:168): running /Users/j-hui/Library/Application Support/pipx/venvs/pass2csv/bin/python -m pip --no-input install pass2csv
pipx >(run_subprocess:168): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:339): get_venv_metadata_for_package: 21ms
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: pass2csv
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(needs_upgrade:78): Time since last upgrade of shared libs, in seconds: 555. Upgrade will be run by pipx if greater than 2592000.
pipx >(run_subprocess:168): running <checking pip's availability>
  installed package pass2csv 1.0.0, installed using Python 3.12.1
  These apps are now globally available
    - pass2csv
done! ✨ 🌟 ✨

$ pass2csv
zsh: /Users/j-hui/.local/bin/pass2csv: bad interpreter: /Users/j-hui/Library/Application: no such file or directory
```

This is due to the unescaped whitespace in the shebang:

```console
$ head -n3 /Users/j-hui/.local/bin/pass2csv
#!/Users/j-hui/Library/Application Support/pipx/venvs/pass2csv/bin/python
import argparse
import csv
```

(But it seems like escaping whitespace in the shebang is not actually supported.)

**Expected behavior**

It should work.

**Comment by j-hui** [comment] 2024-01-16 14:06
Related: https://github.com/conda/conda/issues/186

**Comment by chrysle** [comment] 2024-01-16 14:54
Duplicate of #1198. The workaround is now [documented](https://pipx.pypa.io/latest/troubleshooting/#macos-issues).

**Comment by Gitznik** [comment] 2024-01-16 16:03
Does this actually fix it @j-hui @chrysle? `/Users/j-hui/.local/bin/pass2csv` is an entry point file that pipx generates and specifies the shebang I think. Symlinking won't change the file that pipx generates.

The docs are for using a pipx managed application within another shebang.

**Comment by chrysle** [comment] 2024-01-16 17:06
Right, I missed that, sorry.

> `/Users/j-hui/.local/bin/pass2csv` is an entry point file that pipx generates

Actually, it is the [script created by the venv](https://docs.python.org/3/library/venv.html#how-venvs-work) to run the application, copied into the local bin directory. I think we should patch the path given to the method exposing the script:

https://github.com/pypa/pipx/blob/950c9b0349108ada3ddee8c283711f47353e5570/src/pipx/commands/common.py#L56

Although that would require that the pipx home directory is always symlinked.

**Comment by Gitznik** [comment] 2024-01-16 17:13
There is an issue in iterm2 where the resolution was to symlink to `.config/iterm2` when install iterm. We could go down a similar route.

**Comment by chrysle** [comment] 2024-01-25 17:51
Thanks for reproducing! Sounds good. Since the author recommends installing `pass2csv` via `pipx`, we should probably nudge them towards providing a [`pipx`-compatible entry point](https://pipx.pypa.io/stable/how-pipx-works/#developing-for-pipx).

Also, the linked entry point section is somewhat outdated, since it describes `setupy.py` usage (while you can of course also define entry points in the today recommended `pyproject.toml`). We should update it.

**Comment by Gitznik** [comment] 2024-01-25 18:14
Sweet. I'll split this into separate issues and close this one.

**Closed by Gitznik** 2024-01-25 18:14 UTC
Labels: bug, macOS
