### ISSUE TITLE
Running `pipx list` takes more than 6 minutes to complete

### ISSUE THREAD

**Issue by YUKI2eN3e** [pypa/pipx#1314] opened 2024-03-30 06:08 UTC
**Describe the bug**
I realized that while I frequently update my `pipx` installed programs I hadn't actually updated `pipx` itself for quite some time. I upgraded it and all my installed programs seem to run file, but now `pipx list` takes way longer to run (6m 26s 478ms last time). I haven't tested every `pipx` command so I'm not sure if `pipx list` is the only one but it's certainly the most noticeable.

**How to reproduce**

**Expected behavior**
To be able to quickly list installed programs.

**Comment by chrysle** [comment] 2024-03-30 07:07
Could you post the output of `pipx list -vv`?

**Comment by YUKI2eN3e** [comment] 2024-03-30 19:56
Here's the output of 
```powershell
$(pipx list -vv) *>&1 > pipx_list_-vv.txt
```
in PowerShell 7.4.1 on Windows 10: [pipx_list_-vv.txt](https://github.com/pypa/pipx/files/14813164/pipx_list_-vv.txt)
The only other thing that I can think of besides the version that has changed is that I enabled symlinks for another program and I assume `pipx` is using that since it's not complaining as much about "symlink missing or pointing to unexpected location" as it used to.

**Comment by chrysle** [comment] 2024-03-30 20:49
That's strange, I can't reproduce this behaviour on my Debian machine. Would like others running into this issue to chime in.

We [reverted](https://pipx.pypa.io/stable/installation/#installation-options) usage of `platformdirs` for the `pipx` paths in 1.5.0. Could you try whether migrating your installation to the "new old" paths achieves a better performance, in case you aren't still using them?

**Comment by YUKI2eN3e** [comment] 2024-03-30 23:57
Do you mean move all the "~/.local/pipx" subfolders to AppData?

**Comment by Gitznik** [comment] 2024-03-31 15:07
> Do you mean move all the "~/.local/pipx" subfolders to AppData?

AppData is actually the "old" path we migrated away from. You should be fine on `~/.local/pipx`.

That said, I could not reproduce this issue on a windows VM I spun up.

**Comment by YUKI2eN3e** [comment] 2024-03-31 17:26
Is there any easy way to export all the installed programs and their injected packages so I could try completely uninstalling and reinstalling `pipx` to see if that does anything?

**Comment by chrysle** [comment] 2024-03-31 18:32
> Is there any easy way to export all the installed programs and their injected packages so I could try completely uninstalling and reinstalling `pipx` to see if that does anything?

There will be soon, it's being worked on in #1301.

**Comment by Gitznik** [comment] 2024-04-02 08:02
Will close this issue, as the problem described here is not pipx related :+1:

**Closed by Gitznik** 2024-04-02 08:02 UTC
Labels: windows, need reproduce

**Comment by YUKI2eN3e** [comment] 2024-04-06 23:12
Just wondering if this would work as a solution until `pipx install-all` is ready.

If I run `pipx list --include-injected --json > pipx_list_include-injected.json` to export everything, completely uninstall `pipx` and clear any related folders, then run the output of the following python script I should end up with a clean install will all my current programs right? (Since most of them are still running I thought it better to check instead of just deleting `pipx` and hoping I didn't mess-up anywhere.) 

```python
#!/usr/bin/env python3
import json

with open("pipx_list_include-injected.json", 'r', encoding="utf-8-sig") as file:
    data = json.load(file)

programs = data["venvs"]
filtered = []

for program_name in programs.keys():
    md = programs[program_name]["metadata"]
    p = {"package_or_url": md["main_package"]["package_or_url"]}
    if md["injected_packages"] != {}:
        p["injected_packages"] = []
        for ip in md["injected_packages"].keys():
            p["injected_packages"].append(md["injected_packages"][ip]["package_or_url"])
    filtered.append(p)

for p in filtered:
    print(f'pipx install "{p["package_or_url"]}"')
    if len(p.keys()) > 1:
        main_package_name = p["package_or_url"].split("[")[0].strip() if '[' in p["package_or_url"] else p["package_or_url"].strip()
        cmd_str = f'pipx inject "{main_package_name}"'
        for i in p["injected_packages"]:
            cmd_str = f'{cmd_str.strip()} "{i}"'
        if cmd_str.strip() != f'pipx inject "{main_package_name}"'.strip():
            print(cmd_str.strip())
```

It results in output like this:
```
...
pipx install "E:\Python3\are-in-folder\dist\are_in_folder-0.1.0-py3-none-any.whl"
...
pipx install "glances[all]"
pipx inject "glances" "windows-curses"
...
pipx install "ipython"
pipx inject "ipython" "beautifulsoup4" "pyjwt" "pymediainfo" "requests" "rich"
...
pipx install "git+https://github.com/internetarchive/openlibrary-client.git"
...
```

**Comment by Gitznik** [comment] 2024-04-07 09:23
The mentioned PR has been merged already. You can install pipx from the main branch and already use the command before we actually release it :)

**Comment by YUKI2eN3e** [comment] 2024-04-08 19:56
Ok, so I've tried reinstalling everything but it's still taking over 6 minutes to run `pipx list`...
Would having a non standard "PIPX_MAN_DIR" be able to effect `pipx list`?
Currently it's setup like this:
```
Virtual Environment location is C:\Users\USER\.local\pipx\venvs.
Symlinks to apps are placed in C:\Users\USER\.local\bin.
Symlinks to manual pages are placed in C:\Users\USER\share\man.
```
Should I try changing that and reinstalling again?
