### ISSUE TITLE
pipx install ansible the bin link to ansible-community not ansible

### ISSUE THREAD

**Issue by xin3liang** [pypa/pipx#968] opened 2023-04-14 09:54 UTC
**Describe the bug**

pipx install ansible the bin link to ansible-community not ansible.
```
$ ls -l ~/.local/bin/
lrwxrwxrwx 1 ubuntu ubuntu   60 Apr 14 08:50 ansible-community -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible-community
```

**How to reproduce**

`pipx install ansible`

**Expected behavior**

Expect it to link to ansible so that we can run ansible directly as `pip install ansible`
```
$ ls -l ~/.local/bin/
lrwxrwxrwx 1 ubuntu ubuntu   60 Apr 14 08:50 ansible -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible
```

**Comment by xin3liang** [comment] 2023-04-14 09:58
Looks like `pipx install --include-deps ansible` works.
```
$ pipx install --include-deps ansible
  installed package ansible 7.4.0, installed using Python 3.10.6
  These apps are now globally available
    - ansible
    - ansible-community
    - ansible-config
    - ansible-connection
    - ansible-console
    - ansible-doc
    - ansible-galaxy
    - ansible-inventory
    - ansible-playbook
    - ansible-pull
    - ansible-test
    - ansible-vault
done! ✨ 🌟 ✨
ls -l ~/.local/bin/
lrwxrwxrwx 1 ubuntu ubuntu   50 Apr 14 09:51 ansible -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible
lrwxrwxrwx 1 ubuntu ubuntu   60 Apr 14 09:51 ansible-community -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible-community
lrwxrwxrwx 1 ubuntu ubuntu   57 Apr 14 09:51 ansible-config -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible-config
lrwxrwxrwx 1 ubuntu ubuntu   61 Apr 14 09:51 ansible-connection -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible-connection
lrwxrwxrwx 1 ubuntu ubuntu   58 Apr 14 09:51 ansible-console -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible-console
lrwxrwxrwx 1 ubuntu ubuntu   54 Apr 14 09:51 ansible-doc -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible-doc
lrwxrwxrwx 1 ubuntu ubuntu   57 Apr 14 09:51 ansible-galaxy -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible-galaxy
lrwxrwxrwx 1 ubuntu ubuntu   60 Apr 14 09:51 ansible-inventory -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible-inventory
lrwxrwxrwx 1 ubuntu ubuntu   59 Apr 14 09:51 ansible-playbook -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible-playbook
lrwxrwxrwx 1 ubuntu ubuntu   55 Apr 14 09:51 ansible-pull -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible-pull
lrwxrwxrwx 1 ubuntu ubuntu   55 Apr 14 09:51 ansible-test -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible-test
lrwxrwxrwx 1 ubuntu ubuntu   56 Apr 14 09:51 ansible-vault -> /home/ubuntu/.local/pipx/venvs/ansible/bin/ansible-vault

```

**Comment by meowmeowmeowcat** [comment] 2023-04-15 01:49
Duplicate of #20

**Closed by meowmeowmeowcat** 2023-04-15 01:49 UTC
