### ISSUE TITLE
Installing from git repo (using ssh) hangs forever

### ISSUE THREAD

**Issue by nhumrich** [pypa/pipx#704] opened 2021-06-07 19:31 UTC
**Describe the bug**

Installing from git repo (using ssh) hangs forever. This only happens if you have steps in the ssh that require user input.
For example, if you have to type a password for your ssh key, or you have to type "yes" to accept a host key.

If there are no manual steps needed for ssh, there is no issue. 

**How to reproduce**
try to install a packages using a git ssh url, for example: 

```
pipx install git+ssh://git@gitlab.com/someuser/someproject.git
```

but make sure that your ssh key requires a password, and isn't on your toolchain. 

Then pipx will hang forever, appearing like it is trying to do something.

**Expected behavior**
It should prompt you for your ssh password. 

My guess is this is happening because stdout isn't being piped to the current process and stdin isn't being piped back to the subprocess.

**Comment by itsayellow** [comment] 2021-06-10 01:28
Duplicate of #219.  Valid, but follow-ups should go to that Issue.

I believe the workaround that should work for you would be to use pipx's `--verbose` option as described in #219 .

**Closed by itsayellow** 2021-06-10 01:28 UTC
