### ISSUE TITLE
`pipx` stuck during `install`

### ISSUE THREAD

**Issue by SinTan1729** [pypa/pipx#1309] opened 2024-03-28 21:30 UTC
**Describe the bug**

When I do `pipx install`, it gets stuck. For example, `pipx install papis` gets stuck for a long time. It seems to work at the end though.

**How to reproduce**
Run `pipx install papis --verbose` to get the following output.
```
pipx >(setup:801): pipx version is 1.2.0
pipx >(setup:802): Default python interpreter is '/usr/bin/python3'
pipx >(package_name_from_spec:322): Determined package name: papis
pipx >(package_name_from_spec:323): Package name determined in 0.0s
creating virtual environment...
pipx >(run_subprocess:173): running /usr/bin/python3 -m venv --without-pip /home/sintan/.local/pipx/venvs/papis
pipx >(run_subprocess:173): running /home/sintan/.local/pipx/venvs/papis/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:173): running /home/sintan/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:173): running /home/sintan/.local/pipx/venvs/papis/bin/python --version
pipx >(_parsed_package_to_package_or_url:147): cleaned package spec: papis
installing papis...
pipx >(run_subprocess:173): running /home/sintan/.local/pipx/venvs/papis/bin/python -m pip install papis
```
This is where it gets stuck for several minutes. Then we finally get the following.
```
pipx >(run_subprocess:173): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:316): get_venv_metadata_for_package: 177ms
pipx >(_parsed_package_to_package_or_url:147): cleaned package spec: papis
pipx >(needs_upgrade:69): Time since last upgrade of shared libs, in seconds: 98959. Upgrade will be run by pipx if greater than 2592000.
  installed package papis 0.13, installed using Python 3.11.8
  These apps are now globally available
    - papis
done! ✨ 🌟 ✨
```
**Expected behavior**

It should just install quickly.

**Note**

This is only happening on one of my machines. The others work fine. So maybe there's a local issue. I'm running EndeavourOS on it with kernel `6.8.2-arch1-1`.

**Comment by Gitznik** [comment] 2024-03-28 21:42
Hi @SinTan1729, thanks for raising this.

How fast is it in comparison when you just run `python -m pip install papis` into a virtual environment?

**Comment by SinTan1729** [comment] 2024-03-28 21:57
Hi @Gitznik, looks like that's also taking a long time. So, this might not be a `pipx` bug at all.

**Comment by Gitznik** [comment] 2024-03-28 22:11
Yes, does not seem to be related to pipx in that case.

Best of luck figuring out the cause :+1:  Will close this for now.

**Closed by Gitznik** 2024-03-28 22:11 UTC
Labels: more info from user needed, need reproduce

**Comment by SinTan1729** [comment] 2024-03-31 23:33
Just in case anyone faced this in the future, this was fixed by prioritizing `ipv4` over `ipv6`. Edit `/etc/gai.conf` and uncomment the line `precedence ::ffff:0:0/96  100`.
