### ISSUE TITLE
pipx enters in infinite loop when trying to install a package on python distributed with MSYS2 on Windows

### ISSUE THREAD

**Issue by daniel-a-melo** [pypa/pipx#701] opened 2021-06-02 19:47 UTC
**Describe the bug**
When using MSYS2, package mingw-w64-x86_64-python (https://packages.msys2.org/package/mingw-w64-x86_64-python), pipx enters in infinite loop when installing a package.

```
pipx install pycowsay --verbose
pipx >(setup:717): pipx version is 0.16.3
pipx >(setup:718): Default python interpreter is 'c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe'
pipx >(package_name_from_spec:323): Determined package name: pycowsay
pipx >(package_name_from_spec:324): Package name determined in 0.0s
creating virtual environment...
pipx >(run_subprocess:135): running c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe -m venv --without-pip C:/Users/user1/.local/pipx/venvs/pycowsay
creating shared libraries...
pipx >(run_subprocess:135): running c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe -m venv --clear C:/Users/user1/.local/pipx/shared
creating shared libraries...
pipx >(run_subprocess:135): running c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe -m venv --clear C:/Users/user1/.local/pipx/shared
creating shared libraries...
pipx >(run_subprocess:135): running c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe -m venv --clear C:/Users/user1/.local/pipx/shared
creating shared libraries...
pipx >(run_subprocess:135): running c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe -m venv --clear C:/Users/user1/.local/pipx/shared
creating shared libraries...
pipx >(run_subprocess:135): running c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe -m venv --clear C:/Users/user1/.local/pipx/shared
creating shared libraries...
pipx >(run_subprocess:135): running c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe -m venv --clear C:/Users/user1/.local/pipx/shared
(...)
```

if I execute manually the command `python3.exe -m venv --clear C:/Users/user1/.local/pipx/shared` it is executed successfully

```
c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe -m venv --clear C:/Users/user1/.local/pipx/shared
Looking in links: c:\Users\user1\AppData\Local\Temp\tmphnr44wk9
Processing c:\users\user1\appdata\local\temp\tmphnr44wk9\setuptools-49.2.1-py3-none-any.whl
Processing c:\users\user1\appdata\local\temp\tmphnr44wk9\pip-20.2.3-py2.py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-20.2.3 setuptools-49.2.1
```

Contents of pipx logs:

```
   381.0ms (setup:715): 2021-06-02 20:15:15
   381.0ms (setup:716): C:\Users\user1\.local\bin\pipx install pycowsay
   381.0ms (setup:717): pipx version is 0.16.3
   381.0ms (setup:718): Default python interpreter is 'c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe'
   383.0ms (package_name_from_spec:323): Determined package name: pycowsay
   383.0ms (package_name_from_spec:324): Package name determined in 0.0s
   385.0ms (run_subprocess:135): running c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe -m venv --without-pip C:/Users/user1/.local/pipx/venvs/pycowsay
   843.1ms (run_subprocess:148): stdout:
   844.1ms (run_subprocess:150): stderr:
   844.1ms (run_subprocess:151): returncode: 0
   846.1ms (run_subprocess:135): running c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe -m venv --clear C:/Users/user1/.local/pipx/shared
 16771.8ms (run_subprocess:148): stdout: Looking in links: c:\Users\user1\AppData\Local\Temp\tmpxbeu6b31
Processing c:\users\user1\appdata\local\temp\tmpxbeu6b31\setuptools-49.2.1-py3-none-any.whl
Processing c:\users\user1\appdata\local\temp\tmpxbeu6b31\pip-20.2.3-py2.py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-20.2.3 setuptools-49.2.1
 16771.8ms (run_subprocess:150): stderr:
 16772.8ms (run_subprocess:151): returncode: 0
 16774.8ms (run_subprocess:135): running c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe -m venv --clear C:/Users/user1/.local/pipx/shared
 34595.2ms (run_subprocess:148): stdout: Looking in links: c:\Users\user1\AppData\Local\Temp\tmpreoye3oe
Processing c:\users\user1\appdata\local\temp\tmpreoye3oe\setuptools-49.2.1-py3-none-any.whl
Processing c:\users\user1\appdata\local\temp\tmpreoye3oe\pip-20.2.3-py2.py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-20.2.3 setuptools-49.2.1
 34595.2ms (run_subprocess:150): stderr:
 34595.2ms (run_subprocess:151): returncode: 0
 34597.2ms (run_subprocess:135): running c:/users/user1/software/tools/msys64/mingw64/bin/python3.exe -m venv --clear C:/Users/user1/.local/pipx/shared
 51837.0ms (run_subprocess:148): stdout: Looking in links: c:\Users\user1\AppData\Local\Temp\tmp_75yare0
Processing c:\users\user1\appdata\local\temp\tmp_75yare0\setuptools-49.2.1-py3-none-any.whl
Processing c:\users\user1\appdata\local\temp\tmp_75yare0\pip-20.2.3-py2.py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-20.2.3 setuptools-49.2.1
 51838.0ms (run_subprocess:150): stderr:
 51838.0ms (run_subprocess:151): returncode: 0
 (
 (...)
```

I have seen a similar issue happen with this particular python distribution (MSYS2) and other tools. For example  https://github.com/python-poetry/poetry/issues/2867

This distribution has one particularity. Although it is built for Windows, venvs created with it have POSIX-style:

```
user1@HOST ~/A/L/p/C/v/somevenv> ls -al
total 5
drwxr-xr-x 1 user1 user1   0 Aug 29 23:05 ./
drwxr-xr-x 1 user1 user1   0 Aug 29 23:05 ../
drwxr-xr-x 1 user1 user1   0 Aug 29 23:06 bin/
drwxr-xr-x 1 user1 user1   0 Aug 29 23:05 include/
drwxr-xr-x 1 user1 user1   0 Aug 29 23:05 lib/
-rw-r--r-- 1 user1 user1 106 Aug 29 23:05 pyvenv.cfg
````

The venvs created with have `lib` and `bin` directories instead of `Scripts` directories.  I suspect that pipx may be expecting a Windows-style venv because the underlying OS is Windows. See https://github.com/pypa/pipx/blob/5e26b3b857a568be7fde40a9ef2caa8f7c0c040d/src/pipx/util.py#L79

it is possible to detect this python distro with sysconfig.get_platform() . It will return mingw . See https://stackoverflow.com/questions/35956180/how-to-determine-the-python-is-mingw-or-official-build

**How to reproduce**

1 - Install MSYS2 on Windows 10
2 - From MSYS shell, install python mingw64 : `pacman -S mingw-w64-x86_64-python` and `pacman -S mingw-w64-x86_64-python-pip`
3 - Install pipx using PIP
4 - `pipx install pycowsay`
5 - The process will never complete and venv will be cleaned and rebuilt in an infinite loop

**Expected behavior**

Install should complete successfully

**Comment by itsayellow** [comment] 2021-06-10 01:24
This is interesting.  From my first look it appears that the mechanism to detect the age of pipx's shared libraries is malfunctioning here, and as a result it keeps trying to reinstall the shared libraries.

Somehow it looks like our shared-libs-age-detection doesn't work on this particular system combo.

Another note.  I use MSYS2 on Windows 10, but I use the python.org downloaded python binaries for Windows, and I've never had this problem.  The key here might be using the mingw64 python interpreters.

**Comment by cs01** [comment] 2021-06-10 15:20
I don’t think it’s an age detection thing because the output should say something along the lines of how old the shared line are and whether they are over the age threshold. I think the lib/bin vs Scripts might be the issue, and pipx just never sees what it thinks it should, thus keeps trying to install it.

**Comment by itsayellow** [comment] 2021-06-10 19:37
Thanks @cs01, that's more specifically correct I now see.

I think I see what's happening here.

First, inside of `_SharedLibs.create()`, we create the venv.  At the end of that, we move on to `_SharedLibs.upgrade()`.
https://github.com/pypa/pipx/blob/5e26b3b857a568be7fde40a9ef2caa8f7c0c040d/src/pipx/shared_libs.py#L42-L52

However `_SharedLibs.upgrade()` has a starting if clause `if not self.is_valid:` that kicks back to `_SharedLibs.create()` if `self.is_valid` is `False`.
https://github.com/pypa/pipx/blob/5e26b3b857a568be7fde40a9ef2caa8f7c0c040d/src/pipx/shared_libs.py#L76-L81

In this way we can get into an infinite loop if always `is_valid==False` after creating the venv.  Thus either we aren't creating a valid shared libs venv, or `_SharedLibs.is_valid()` is likely what's not working properly here based on the logs.

**Comment by itsayellow** [comment] 2021-06-10 19:45
Ah I'm guessing the problem is that the ming64 paths look like POSIX but the code is expecting Windows paths for `_SharedLibs.python_path` and `_SharedLibs.pip_path`.

@daniel-a-melo , can you execute `ls ~/.local/pipx/shared/*` from your MSYS2 prompt and post the result?

**Comment by itsayellow** [comment] 2021-06-10 20:04
Thanks for the info.

Sigh so this is some weird mix of Windows and POSIX, because we have the `bin/` directory instead of `Scripts/`, but at the same time what's inside the `bin/` directory are the classic Windows files (e.g. `Activate.ps1`, and all executables end in `*.exe`).  How confusing.

I have never understood why python on Windows used `Scripts/` Instead of `bin/` anyway, and now this is weird in a new way.  😛

**Comment by itsayellow** [comment] 2021-06-10 20:09
So now because it's just the directory names and not the executable names that are the problem, I believe the real code to drill down to is `pipx.util.get_venv_paths()`.
https://github.com/pypa/pipx/blob/5e26b3b857a568be7fde40a9ef2caa8f7c0c040d/src/pipx/util.py#L77-L90

Is there a more reliable pythonic way to know if we need to look for `Scripts` vs. `bin` in a venv than just checking if we're in Windows?

**Comment by itsayellow** [comment] 2021-06-10 20:29
Perhaps we can leverage the `venv` API inside of `get_venv_paths()` to make this more rock solid.
e.g.
```python
import venv

def get_venv_paths(root: Path) -> Tuple[Path, Path]:
    root_paths = venv.EnvBuilder().ensure_directories(root)
    bin_path = Path(root_paths.bin_path)
    python_path = Path(root_paths.env_exe)
    return bin_path, python_path
```

https://docs.python.org/3.6/library/venv.html#venv.EnvBuilder.ensure_directories

Unfortunately it appears that `ensure_directories` wants to either `clear` or `upgrade` an existing directory.  I can't find an API function that merely gives you information without trying to change things.  We'd either have to create a new throwaway directory to get the dir information, or execute this during a clear or upgrade (which we could do for the shared libs.)

See below for experiments:
```
>>> import venv
>>> a = venv.EnvBuilder().ensure_directories("test")
>>> a
namespace(env_dir='test', env_name='test', prompt='(test) ', executable='/usr/local/opt/python@3.9/bin/python3.9', python_dir='/usr/local/opt/python@3.9/bin', python_exe='python3.9', inc_path='test/include', bin_path='test/bin', bin_name='bin', env_exe='test/bin/python3.9')
>>> a.python_exe
'python3.9'
>>> a.env_exe
'test/bin/python3.9'
>>> a.bin_path
'test/bin'
```

**Comment by itsayellow** [comment] 2021-06-10 21:53
I think that the documentation for `venv.ensure_directories()` is a little wrong.  There is no error if the directories are existing and both `clear=False` and `upgrade=False`.  

There seems to be no ill effects by running `venv.ensure_directories()` on an existing venv.  I went back in the source to before python 3.6 and it seems to do nothing but provide information if the directories are existing, and if `clear=False`.
https://github.com/python/cpython/blob/175ebc60d52f2e88cf5cba5224c15074d2623c10/Lib/venv/__init__.py#L95-L107

**Comment by uranusjr** [comment] 2021-06-12 02:08
I think the documentation is implying the behaviour is undefined if you do `clear=False, upgrade=False` on an existing prefix. It works now, but there’s no guarantee the behaviour would stay valid in the future.

**Comment by itsayellow** [comment] 2021-06-12 02:53
> I think the documentation is implying the behaviour is undefined if you do `clear=False, upgrade=False` on an existing prefix. It works now, but there’s no guarantee the behaviour would stay valid in the future.

Yup, agreed.  Which is unfortunate because it would be a super useful way to get information.

I made an issue and a PR to try and update the documentation of the API, with the idea that possibly this could be the documented behavior of the API.
https://bugs.python.org/issue44388

**Comment by itsayellow** [comment] 2021-08-05 23:50
BTW they merged my documentation update, so I guess now it is a "documented part of the API".  To my mind now we can rely on it.  I like this idea because it is pretty clean and part of the `venv` API.

**Comment by hcoona** [comment] 2021-09-18 06:43
I hit the issue via Python 3.9 installed from Microsoft Store

![image](https://user-images.githubusercontent.com/712433/133879150-1b212d31-ab2d-438a-adb0-33f0b941e53e.png)

**Comment by hcoona** [comment] 2021-09-18 07:02
I added this as a workaround

![image](https://user-images.githubusercontent.com/712433/133879650-927fa1a1-d8fb-471c-bb9c-0b20cd0fb5d9.png)

**Comment by ph4nt0m** [comment] 2022-05-26 14:55
I encountered the same issue today. Has there been any progress following the discussion above? The proposed solution by @itsayellow seemed alright after the docs had been updated:

> Perhaps we can leverage the `venv` API inside of `get_venv_paths()` to make this more rock solid. e.g.
> 
> ```python
> import venv
> 
> def get_venv_paths(root: Path) -> Tuple[Path, Path]:
>     root_paths = venv.EnvBuilder().ensure_directories(root)
>     bin_path = Path(root_paths.bin_path)
>     python_path = Path(root_paths.env_exe)
>     return bin_path, python_path
> ```

**Closed** 2023-02-02 06:55 UTC
Labels: windows

**Comment by Kreijstal** [comment] 2024-10-29 10:47
why does this still enter infinite loop is the problem back? for example installing aider-chat i enter infinite loop.... again
