### ISSUE TITLE
feat: align cli flags with pip

### ISSUE THREAD

**Issue by hitchhooker** [pypa/pipx#1065] opened 2023-09-23 21:55 UTC
```
6993 ± pipx install -r requirements.txt                                                                                   [38d21h31m]
usage: pipx [-h] [--version]
            {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,environment,completions}
            ...
pipx: error: unrecognized arguments: -r
```
would be great if cli worked as drop-in replacement to pip

**Comment by dukecat0** [comment] 2023-09-24 04:48
This is a duplicate of #1031.

**Closed by dukecat0** 2023-09-24 04:48 UTC
