### ISSUE TITLE
Provide unified way to reinstall a package with source url

### ISSUE THREAD

**Issue by glensc** [pypa/pipx#902] opened 2022-10-17 00:29 UTC
**How would this feature be useful?**

When installing from a branch, force update to the latest commit of the branch.

**Describe the solution you'd like**

Similarly to https://github.com/pypa/pipx/issues/741 provide a unified way to install or upgrade the package (regardless what is installed) when using the source URL format.

**Describe alternatives you've considered**

Currently, there are several issues:
1. `install --force`, does not actually pull in new changes, even UI shows it's doing something it does not pick up new changes from the branch
2. `reinstall` has no `--suffix` support, so there's no equivalent to `install --force --suffix`
3. totally dumb workaround is to `uninstall` and then `install` again.

outputs of the commands mentioned:

```
$ pipx --version
1.1.0

# first install
$ pipx install --suffix=@1104 --force git+https://github.com/Taxel/PlexTraktSync@refs/pull/1104/head
⣟ installing PlexTraktSync from spec 'git+https://github.com/Taxel/PlexTraktSync@refs/pull/1104/head'
  installed package PlexTraktSync 0.22.0.dev0 (PlexTraktSync@1104), installed using Python 3.10.7
  These apps are now globally available
    - plextraktsync@1104
done! ✨ 🌟 ✨

# second install (does not actually pull new changes even if pull/1104 has new commits)
$ pipx install --suffix=@1104 --force git+https://github.com/Taxel/PlexTraktSync@refs/pull/1104/head
Installing to existing venv 'PlexTraktSync@1104'
  installed package PlexTraktSync 0.22.0.dev0 (PlexTraktSync@1104), installed using Python 3.10.7
  These apps are now globally available
    - plextraktsync@1104
done! ✨ 🌟 ✨

# reinstall does not support --suffix
$ pipx reinstall --suffix=@1104 git+https://github.com/Taxel/PlexTraktSync@refs/pull/1104/head
usage: pipx [-h] [--version]
            {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,environment,completions}
            ...
pipx: error: unrecognized arguments: --suffix=@1104
```

**Comment by meowmeowmeowcat** [comment] 2022-10-23 04:32
This is probably a duplicate of https://github.com/pypa/pipx/issues/582.

**Comment by glensc** [comment] 2022-10-23 11:17
yeah, in this case would not want to re-create venv, but rather just update git pointer of the checkout

**Comment by chrysle** [comment] 2023-07-03 11:31
@dukecat0 Please close this and #929

**Closed** 2023-07-03 11:33 UTC
