### ISSUE TITLE
change default pip upgrade strategy

### ISSUE THREAD

**Issue by cs01** [pypa/pipx#254] opened 2019-10-27 19:22 UTC
**How would this feature be useful?**

When upgrading packages, currently only the main package is upgraded, and dependent packages are only upgraded if needed. This will potentially cause end users to miss out on new features and security patches.

**Describe the solution you'd like**

pip allows for configurable upgrade strategies: https://pip.pypa.io/en/stable/reference/pip_install/
```
--upgrade-strategy <upgrade_strategy>
Determines how dependency upgrading should be handled [default: only-if-needed]. “eager” - dependencies are upgraded regardless of whether the currently installed version satisfies the requirements of the upgraded package(s). “only-if-needed” - are upgraded only when they do not satisfy the requirements of the upgraded package(s).
```

pipx should pass this value default.

**Describe alternatives you've considered**

Users can manually pass the argument to pip via pipx 
```
pipx upgrade PACKAGE --pip-args='--upgrade-strategy eager'
```
but this is cumbersome and requires education. Users don't fall into the "pit of success" here.

**Comment by itsayellow** [comment] 2019-10-29 23:42
The default was apparently changed with pip 10.0.  The reason for it was that things occasionally broke with the eager strategy:
https://pip.pypa.io/en/stable/user_guide/#only-if-needed-recursive-upgrade
>The default strategy is only-if-needed. This was changed in pip 10.0 due to the breaking nature of eager when upgrading conflicting dependencies.

This was my original worry, the whole point of projects like pipenv from what I understand is that pip isn't doing any kind of sophisticated dependency resolution.

**Comment by gaborbernat** [comment] 2023-12-02 18:02
Duplicate of https://github.com/pypa/pipx/issues/925

**Closed by gaborbernat** 2023-12-02 18:02 UTC
