### ISSUE TITLE
ensurepath creates double entries in the path

### ISSUE THREAD

**Issue by floatingpurr** [pypa/pipx#351] opened 2020-02-03 16:04 UTC
Hi guys, I run into a potential problem w/ the command

```bash
$ pipx ensurepath
```
**More context:**

- OS: macOS Catalina 10.15.2 
- Shell: zsh 5.7.1

**Describe the bug**
When I run `ensurepath` the path `$HOME/.local/bin` is inserted twice both in `.zshrc` and in `.zprofile`

Then, my path is polluted with doubled entries

```bash
<other_stuff>:/Users/myuser/.local/bin:/Users/myuser/.local/bin
```

**How to reproduce**
```bash
$ python -m pip install pipx
$ pipx ensurepath
```

**Expected behavior**
Just one entry of `/Users/myuser/.local/bin` should be added to the path.

**Comment by ciarancourtney** [comment] 2020-02-18 06:59
Same on Windows 10

**Comment by ralish** [comment] 2020-05-09 09:34
Saw the same with several dozen entries in my system `PATH` being duplicated into my user `PATH`.

The cause is actually a bug in the `userpath` library used by `pipx`. I've opened an issue here:
https://github.com/ofek/userpath/issues/23

**Comment by ofek** [comment] 2020-05-09 15:03
@ciarancourtney @ralish Windows is fixed in `1.4.0` (see https://github.com/ofek/userpath/pull/24)

The OP's issue is different https://github.com/ofek/userpath/issues/3#issuecomment-512928319

**Comment by ralish** [comment] 2020-05-09 21:27
Confirming this is fixed (on Windows) with `userpath` 1.4.0. Thanks @ofek!

**Comment by floatingpurr** [comment] 2020-06-01 11:22
Not fixed for macOS

**Comment by meowmeowmeowcat** [comment] 2022-08-01 08:21
@floatingpurr Do you still encounter this issue?

**Comment by floatingpurr** [comment] 2022-08-01 09:11
Hi @meowmeowmeowcat. To be honest, off the top of my head, I can't remember. Next time I'll check it out. However, this is an old issue. I guess that if anybody has experienced something similar anymore, everything should be fine now. I'm gonna close it for now. Thanx for asking.

**Comment by floatingpurr** [comment] 2022-09-02 10:03
Ok, just tried. When I run `ensurepath`, an entry like the following one:

```
# Created by `pipx` on 2022-09-02 09:58:37
export PATH="$PATH:/Users/floatingpurr/.local/bin"
```

is appended to both `.zshrc` and `.zprofile`.

Is that the expected behavior?

**Comment by meowmeowmeowcat** [comment] 2022-09-09 12:22
https://github.com/ofek/userpath/issues/3#issuecomment-512938672

**Closed** 2022-09-09 13:17 UTC
Labels: upstream
